name: OrchidWatch
options:
  xcodeVersion: "15.4"
  deploymentTarget:
    watchOS: "8.0"
targets:
  OrchidWatch:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "8.0"
    info:
      path: WatchApp-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.generic.projectorchid.watchkitapp
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.generic.projectorchid
        INFOPLIST_KEY_WKWatchKitApp: YES
        TARGETED_DEVICE_FAMILY: 4
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        SKIP_INSTALL: NO
    dependencies:
      - target: OrchidWatchExtension
        embed: true
  OrchidWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - OrchidWatchApp.swift
    info:
      path: WatchExtension-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.generic.projectorchid.watchkitapp.watchkitextension
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: 4
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        SKIP_INSTALL: YES
        ARCHS: armv7k
        ONLY_ACTIVE_ARCH: YES
